### ISSUE TITLE
CustomRowComponent does NOT get handed state

### ISSUE THREAD

**Issue by sww314** [GriddleGriddle/Griddle#668]
## Griddle version
1.5 and 1.3 (works in 1.0.3)

## Expected Behavior
Customize row to make it look like a list. The rowDataSelector is not getting handed the state objects (I think).
Follow the code here in the documentation:
https://github.com/GriddleGriddle/griddle-docs/blob/master/components/GriddleList.js

## Actual Behavior
    const CustomRowComponent = connect((state, props) => ({
      rowData: plugins.LocalPlugin.selectors.rowDataSelector(state, props),
    }))(({ rowData }) => (
      <HotelDetail
        hotel={rowData}
        selectHotel={this.selectHotelList}
        favoriteHotel={this.favHotel}
      />
    ));
.....

```
 <Griddle
      data={this.props.hotels}
      pageProperties={{
        pageSize: 60,
      }}
      plugins={[plugins.LocalPlugin]}
      sortProperties={sortProperties}
      components={{
        Row: CustomRowComponent,
        TableContainer: CustomTableComponent,
        TableBody: CustomTableBody,
        SettingsToggle: () => <span />,
      }}
    />
```

TypeError: state.get is not a function
    at Object.rowDataSelector (dataSelectors.js:289)
    at Function.mapToProps (HotelList.js:28)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:52)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at handleFirstCall (selectorFactory.js:26)
    at pureFinalPropsSelector (selectorFactory.js:74)
    at Object.runComponentSelector [as run] (connectAdvanced.js:26)
    at Connect.initSelector (connectAdvanced.js:178)
    at new Connect (connectAdvanced.js:119)

## Steps to reproduce
Run the example in the Documentation
https://github.com/GriddleGriddle/griddle-docs/blob/master/components/GriddleList.js
 
## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by thelittleblacksmith** [comment]
We're getting this error as well. For now, removing `plugins.LocalPlugin` from the plugins prop renders the data as a card list but obviously removes the filtering feature.

(It's really strange because one person has managed to get everything working -- card list and filtering -- but anyone else who clones the repo gets this error.)

**Comment by sww314** [comment]
I had to downgrade to 1.0.3 to get this work again. Looks like it is broken in 1.3 and 1.5 (atleast for my use case.)

**Comment by dahlbyk** [comment]
@sww314 @thelittleblacksmith I'm not sure what to tell you. I tried to reproduce this in https://github.com/GriddleGriddle/Griddle/pull/676, but everything seems to be working as expected. I wonder if it's related to other dependencies?

```
$ npm ls --depth=0
griddle-react@1.5.0 C:\Dev\OSS\Griddle
+-- @kadira/storybook@2.35.3
+-- @types/react@15.0.23
+-- ava@0.17.0
+-- babel-cli@6.24.1
+-- babel-core@6.24.1
+-- babel-loader@6.4.1
+-- babel-plugin-lodash@3.2.11
+-- babel-preset-es2015@6.24.1
+-- babel-preset-react@6.24.1
+-- babel-preset-stage-0@6.24.1
+-- babel-register@6.24.1
+-- cross-env@3.2.4
+-- enzyme@2.8.2
+-- eslint@3.19.0
+-- eslint-config-airbnb@14.1.0
+-- eslint-plugin-import@2.2.0
+-- eslint-plugin-jsx-a11y@3.0.2
+-- eslint-plugin-react@6.10.3
+-- immutable@3.8.1
+-- jsdom@9.12.0
+-- jsdom-global@2.1.1
+-- lodash@4.17.4
+-- lodash-webpack-plugin@0.11.3
+-- max-safe-integer@1.0.1
+-- node-libs-browser@2.0.0
+-- prop-types@15.5.8
+-- react@15.5.4
+-- react-addons-test-utils@15.5.1
+-- react-dom@15.5.4
+-- react-redux@5.0.4
+-- recompose@0.21.2
+-- redux@3.6.0
+-- reselect@2.5.4
+-- rimraf@2.6.1
+-- ts-loader@2.0.3
+-- typescript@2.3.2
+-- webpack@1.15.0
`-- webpack-dev-server@1.16.5
```

**Comment by archy-bold** [comment]
I think it's related to https://github.com/GriddleGriddle/Griddle/issues/626.

**Comment by thelittleblacksmith** [comment]
@dahlbyk 

So we kind of figured out what was happening with us (even though it doesn't really make sense?). When we incorporated Griddle, I started with `1.0.3` then upgraded it to `1.5` because I needed access to `cssClassName`. My teammate did an npm install from that package.json (which had version `1.5`) and got that `set.get()` error. We downgraded to `1.0.3` as per @sww314 and my teammate didn't have that error anymore. 

Today, on a hunch, we both manually upgraded to `@latest` and the list display is now working for both of us. I'm not really sure what's happening, but did you need to see a list of our dependencies as well?

**Comment by dahlbyk** [comment]
If `@latest` is working I'm not sure how much effort we should spend on it.

**Comment by sww314** [comment]
I removed griddle and the read added it. What is weird is that only 1.3.1 appears available now...
<img width="402" alt="screen shot 2017-06-14 at 10 07 25 am" src="https://user-images.githubusercontent.com/1430264/27139709-58a641c4-50e9-11e7-9972-a7c926da4727.png">

However, 1.3.1 works when on a clean install.  My guess is the issue was related to a dependency or build problem in the 1.5 package.

Scotts-MBP-2:catch-js swhite$ yarn add griddle-react
yarn add v0.20.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 10 new dependencies.
├─ change-emitter@0.1.6
├─ fbjs@0.8.12
├─ griddle-react@1.3.1
├─ hoist-non-react-statics@1.2.0
├─ max-safe-integer@1.0.1
├─ react-redux@5.0.5
├─ recompose@0.21.2
├─ redux@3.6.0
├─ reselect@2.5.4
└─ symbol-observable@1.0.4
✨  Done in 17.29s.

**Comment by sww314** [comment]
Ugh. This is some type of problem with the webpack bundling that causes the problem. It is back now and I have not changed any Griddle code.

**Comment by ryanlanciaux** [comment]
Hmm - sorry you're running into this :| I was running into some weirdness on docs project as described in the issue so latest is @1.3.1 until that gets resolved (I'm using 1.5.0 in some of my projects, though without any trouble). 

I will try to dig into this a bit more by this weekend if not sooner.

**Comment by ryanlanciaux** [comment]
If anyone gets there first, though, that's cool :)
