### ISSUE TITLE
Run from source

### ISSUE THREAD

**Issue by sum32** [GriddleGriddle/Griddle#777]
## Griddle version
source 2017-12-17, 1e6346a Merge pull request #771 from dahlbyk/gh672
## Expected Behavior
Story book should work
## Actual Behavior
ERROR in ./stories/index.tsx
(923,31): error TS2339: Property 'searchString' does not exist on type '{}'.

ERROR in ./stories/index.tsx
(947,22): error TS2339: Property 'searchString' does not exist on type '{}'.

ERROR in ./stories/index.tsx
(947,43): error TS2339: Property 'data' does not exist on type '{}'.

ERROR in ./stories/index.tsx
(948,17): error TS2339: Property 'data' does not exist on type '{}'.

ERROR in ./stories/index.tsx
(949,76): error TS2339: Property 'searchString' does not exist on type '{}'.
## Steps to reproduce
`git clone https://github.com/GriddleGriddle/Griddle.git && cd Griddle && npm install && npm run storybook`
I use node v8.9.3

> > start-storybook -p 6006
> 
> @kadira/storybook v2.35.3
> 
> => Loading custom .babelrc
> => Loading custom webpack config.
> 
> React Storybook started on => http://localhost:6006/
> 
>  We will collect some anonymous usage stats of how you use storybook.
>  See why?: https://getstorybook.io/tracking
> 
> ts-loader: Using typescript@2.5.3 and /home/user/workspace/Griddle/tsconfig.json
> webpack built 46757a42dcf954be8b77 in 8341ms
> Hash: 46757a42dcf954be8b77
> Version: webpack 1.15.0
> 

Are there any additional requirements to run from source?

**Comment by rgstephens** [comment]
I'm having the same issue on Node 7.10.0

**Comment by dahlbyk** [comment]
Can you share output from `npm ls`?

**Comment by dahlbyk** [comment]
Nevermind, this failure is confirmed by Travis: https://travis-ci.org/GriddleGriddle/Griddle/jobs/308447676. The issue seems like it might be `@types/react-redux@5.0.14`? The [original build](https://travis-ci.org/GriddleGriddle/Griddle/builds/302599777) for https://github.com/GriddleGriddle/Griddle/pull/768 was green.

¯\\\_(ツ)\_/¯

**Comment by dahlbyk** [comment]
Confirmed build was broken by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21400, submitting a fix now.

**Comment by ryanlanciaux** [comment]
Thank you a ton! I saw this broke but couldn't make sense of it just yet.
